# Generated by Django 4.1.2 on 2022-10-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='pdated',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='message',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
